### ISSUE TITLE
TypeError: pyqtSignal must be bound to a QObject, not 'MonitorDashWidget'

### ISSUE THREAD

**Issue by 130s** [PR2/rqt_pr2_dashboard#6]
Happens always when I close `rqt-pr2-dashboard` on `rqt_gui` by selecting "Running" --> "Close: PR2-Dashboard". No action taken on PR2-Dashboard after it's opened.

```
Traceback (most recent call last):
  File "/wg/stor5/isaito/data/Dropbox/ROS/groovy_quantal/catkin_ws/src/rqt_robot_plugins/rqt_robot_dashboard/src/rqt_robot_dashboard/monitor_dash_widget.py", line 99, in _stalled
    self.update_state(3)
  File "/wg/stor5/isaito/data/Dropbox/ROS/groovy_quantal/catkin_ws/src/rqt_robot_plugins/rqt_robot_dashboard/src/rqt_robot_dashboard/icon_tool_button.py", line 100, in update_state
    self.state_changed.emit(self.__state)
TypeError: pyqtSignal must be bound to a QObject, not 'MonitorDashWidget'
```

Ubuntu Quantal 64

All from source
PR2-Dashboard 190aa79c3ae28f3d37bc32b974c36635144cf1f9
rqt_robot_monitor f607ca003b8e97598173371536835ecfae1ecac5
https://github.com/ros-visualization/qt_gui_core/commit/752e595aab1c4efe490556891218e4329bcc1cf1

**Comment by 130s** [comment]
if you received an email of my original issue report, I've updated on web (I referred to wrong software versions in my original post).

**Comment by ablasdel** [comment]
fixed in https://github.com/ros-visualization/rqt_robot_plugins/commit/cc7c38a94efe25e64ed674e1ab09bde645af9514
